name: Build & Deploy
#on: workflow_dispatch
on: ["push"]

jobs:
  build:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    env:
      POSTGRES: ${{ secrets.POSTGRES }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Compile
        run: |
          # compile
          go build

          # build container
          docker build . -t website

          # kill all containers
          containers=$(docker ps -q)
          if [ -n "$containers" ]; then
              docker kill $containers
          fi

          # start new containers
          docker run -d -p8080:8080 -e POSTGRES="${{ secrets.POSTGRES }}" website
