name: Build & Deploy
#on: workflow_dispatch
on: ["push"]

jobs:
  build:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build API Server
        run: |
          # compile
          go build
          docker build . -t api

      - name: Build React App
        run: |
          cd ui
          npm run build
          docker build . -t ui

      - name: Restart Services 
        run: |
          # kill all currently running containers
          containers=$(docker ps -q)
          if [ -n "$containers" ]; then
              docker kill $containers
          fi

          # start new containers
          docker run -d -p8080:8080 \
            -e POSTGRES_DSN="${{ secrets.POSTGRES }}" \
            api