name: Build & Deploy
#on: workflow_dispatch
on: ["push"]

jobs:
  build:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build API Server
        run: |
          pushd api
          make build
          docker build . -t api
          popd

      - name: Build React App
        run: |
          pushd ui
          npm install
          REACT_APP_API_BASE_URL=https://api.scottfrazer.net npm run build
          docker build . -t ui
          popd

      - name: Restart Services 
        run: |
          # kill all currently running containers
          containers=$(docker ps -q)
          if [ -n "$containers" ]; then
              docker kill $containers
          fi

          # start new containers
          docker run -d -p8080:8080 \
            -e POSTGRES_DSN="${{ secrets.POSTGRES }}" \
            -e ADMIN_PASSWORD_BCRYPT="${{ secrets.ADMIN_PASSWORD_BCRYPT }}" \
            api

          docker run -d -p9090:8080 ui